# Notebook on the Neural Network course of Sentdex

In [48]:
import matplotlib as plt
import numpy as np


#### Video 1
On travaille ici sur notre premier neurone avec 3 entrées avec son poid respectif et puis le biais du neurone et enfin sa sorti 
Qu'est ce qu'un neurone ? 
C'est un objet qui fait la multiplication de ses entrées avec leur poids respectif et la somme de ces resultats avec le biais

<img src="./media/video2_1_neurone.png">

In [49]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
biais = 2

output = np.sum([inputs[i] * weights[i] for i in range(0, len(inputs))]) + biais
print(output)


2.3


#### Video 2

les input peuvent etre des données de capteurs

In [50]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1]
biais = 2

output = np.sum([inputs[i] * weights[i] for i in range(0, len(inputs))]) + biais
print(output)


4.8


Et si on faisait 3 neurones avec 4 entrées

![mon_image](./media/video2_4neurones_4entres.png)

In [51]:
inputs = [1, 2 ,3, 2.5]

weights=[
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
    ]

biais = [[2],[3],[0.5]]

output=np.zeros((3,1))

for i in range(0,np.shape(np.array(weights))[0]) :
    output[i][0] = np.sum([inputs[j]*weights[i][j] for j in range(0,len(inputs))]) + biais[i][0]
print(output)

[[4.8  ]
 [1.21 ]
 [2.385]]


In [52]:
biais = [[2], [3], [0.5]]
biais[1][0]


3

#### Video 3

il reecrit avec des loop. Ce que j'avais deja fait ma comme ca j'ai la meme version que dans le cours.
Le tout sans matrice


In [53]:
inputs = [1, 2 ,3, 2.5]

weights=[
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
    ]

biais = [2, 3, 0.5]

layer_output = []
for neuron_weights, neuron_biais in zip(weights, biais):
    neuron_output = neuron_biais
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    layer_output.append(neuron_output)
    
print(layer_output)

[4.800000000000001, 1.21, 2.385]


Maintenat le tout en matrice

In [54]:
inputs = [1, 2 ,3, 2.5]

weights=[
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
    ]

biais = [2, 3, 0.5]


weights_t = np.transpose(np.array(weights))

outputs = inputs @ weights_t + biais

print(outputs)

[4.8   1.21  2.385]


#### Video4

On va maintenant prendre plusieur entrées a la fois. On appelle ça le **batch**

In [55]:
inputs = [[1, 2 ,3, 2.5],
          [2.0, 5.0,-1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights=[
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
    ]

biais = [2, 3, 0.5]

weights_t = np.array(weights).T

outputs = inputs @ weights_t + biais

print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


On veut mettre une nouvelle layer 

In [56]:
weights2=[
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
    ]

biais2 = [-1, 2, -0.5]

inputs = [[1, 2 ,3, 2.5],
          [2.0, 5.0,-1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights=[
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
    ]

biais = [2, 3, 0.5]

weights_t = np.array(weights).T
weights_t2 = np.array(weights2).T

layer_out1 = inputs @ weights_t + biais
layer_out2 = layer_out1 @ weights_t2 + biais2

print(layer_out2)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


On va maintenant faire ça en objets
X : entrée

In [57]:
np.random.seed(0)

X= [[1, 2 ,3, 2.5],
    [2.0, 5.0,-1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]
    
class Layer_Dense:
    def __init__(self,n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = inputs @ self.weights + self.biases
        
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)


[[ 0.14829601 -0.08397602]
 [ 0.14100316 -0.01340469]
 [ 0.20124978 -0.07290616]]


Vdeo 5 : Hidden Layer Activation Functions

test d'une foncton ReLU

In [58]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
outputs=[]
for i in inputs: 
    outputs.append(max(0,i))
print(outputs)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


maintenat on va mettra tout ça la dedans

In [59]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

np.random.seed(0)

X= [[1, 2 ,3, 2.5],
    [2.0, 5.0,-1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

X, y = spiral_data(100,3)
    
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = inputs @ self.weights + self.biases
        
class Activayion_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)
        
layer1 = Layer_Dense(2,5)
#layer2 = Layer_Dense(5,2)

activation1 = Activayion_ReLU()

layer1.forward(X)
print(layer1.output)

activation1.forward(layer1.output)
print(activation1.output)

#layer2.forward(layer1.output)
#print(layer2.output)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452215e-03  4.65504476e-04
   4.56846319e-05]
 [-2.39994470e-03  5.93471341e-05 -2.24808278e-03  2.03573145e-04
   6.10024319e-04]
 ...
 [ 1.13291517e-01 -1.89262286e-01 -2.06855088e-02  8.11079666e-02
  -6.71350881e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493989e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458786e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504476e-04
  4.56846319e-05]
 [0.00000000e+00 5.93471341e-05 0.00000000e+00 2.03573145e-04
  6.10024319e-04]
 ...
 [1.13291517e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493989e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]

#### Video 6 : Softmax activation fonction

softmax ? Pourquoi faire ? Pour faire des choix

In [60]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

np.random.seed(0)

X= [[1, 2 ,3, 2.5],
    [2.0, 5.0,-1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

X, y = spiral_data(100,3)
    
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = inputs @ self.weights + self.biases
        
class Activayion_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
        
        
layer1 = Layer_Dense(2,5)
#layer2 = Layer_Dense(5,2)

activation1 = Activayion_ReLU()

layer1.forward(X)
print(layer1.output)

activation1.forward(layer1.output)
print(activation1.output)

#layer2.forward(layer1.output)
#print(layer2.output)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452215e-03  4.65504476e-04
   4.56846319e-05]
 [-2.39994470e-03  5.93471341e-05 -2.24808278e-03  2.03573145e-04
   6.10024319e-04]
 ...
 [ 1.13291517e-01 -1.89262286e-01 -2.06855088e-02  8.11079666e-02
  -6.71350881e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493989e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458786e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504476e-04
  4.56846319e-05]
 [0.00000000e+00 5.93471341e-05 0.00000000e+00 2.03573145e-04
  6.10024319e-04]
 ...
 [1.13291517e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493989e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]

#### Video 7 : Calculating Loss with Categorical Cross-Entropy

On veux avoir des probabilité es sortie de notre reseaux
Comment savoir de cb otre model est loin? On utilise la categorical cross entropie
L = sum(-log(yi))

**One hot encoding :**

Class : 2 | Label : 0 => One-hot : [***1***, 0] 

Class : 4 | Label : 1 => One-hot : [0, ***1***, 0, 0] 

------
On ajoute maintenant la Prediction a cette algorithme

Class : 3 | Label : 0 => One-hot : [***1***, 0, 0] => Prediction (Soft max): [0.7,0.1, 0.2]

Ici Loss = - (***1*** x log(0.7) + 0 x log(0.1) + 0 x log(0.2)) = 0.35....

**Exemple :**

In [61]:
import math

softmax_output = [0.7, 0.1, 0.2]
#target_class = 0
#cela signifie que 
target_output = [1, 0, 0]

loss = np.sum(-np.log(np.array(softmax_output))*np.array(target_output))
print(loss)

0.35667494393873245


#### Video 8 :

Comment on l'implemente dans notre framework

In [72]:
softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4],
                            [0.02, 0.9, 0.08]])

class_targets = [0, 1, 1]

# print([[0, 1, 2], class_targets])
# print(softmax_outputs)
# print(softmax_outputs[[0, 1, 2]])
# print(softmax_outputs[[0,0,0],1])
# print(softmax_outputs[[choix des ligne],[choix des colonnes]])
#print(range(len(softmax_outputs)), class_targets)
print(-np.log(softmax_outputs[range(len(softmax_outputs)), class_targets]) )   # type: ignore 

[0.35667494 0.69314718 0.10536052]


Comment on gere 0?
On peut bloquer les valeurs

In [77]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

np.random.seed(0)

X= [[1, 2 ,3, 2.5],
    [2.0, 5.0,-1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

X, y = spiral_data(100,3)
    
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = inputs @ self.weights + self.biases
        
class Activayion_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
        
class Loss: 
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)  # type: ignore
        data_loss = np.mean(sample_losses)
        return data_loss
    
class Loss_CategoricalCrossEntropy(Loss): 
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)
        
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods
        
        
X,y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2, 3)
activation1 = Activayion_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

#print(activation2.output[:5])

loss_function = Loss_CategoricalCrossEntropy()

loss = loss_function.calculate(activation2.output, y)

print(loss)



1.0985749
